// Curated list of well-known world cities, used to power the "From" autocomplete
// so users can pick their location instead of risking a misspelling.
const RAW_CITIES = [
  // North America
  "Atlanta, United States",
  "Austin, United States",
  "Baltimore, United States",
  "Boston, United States",
  "Charlotte, United States",
  "Chicago, United States",
  "Cincinnati, United States",
  "Cleveland, United States",
  "Columbus, United States",
  "Dallas, United States",
  "Denver, United States",
  "Detroit, United States",
  "El Paso, United States",
  "Fort Worth, United States",
  "Honolulu, United States",
  "Houston, United States",
  "Indianapolis, United States",
  "Jacksonville, United States",
  "Kansas City, United States",
  "Las Vegas, United States",
  "Los Angeles, United States",
  "Louisville, United States",
  "Memphis, United States",
  "Miami, United States",
  "Milwaukee, United States",
  "Minneapolis, United States",
  "Nashville, United States",
  "New Orleans, United States",
  "New York, United States",
  "Oklahoma City, United States",
  "Orlando, United States",
  "Philadelphia, United States",
  "Phoenix, United States",
  "Pittsburgh, United States",
  "Portland, United States",
  "Raleigh, United States",
  "Sacramento, United States",
  "Salt Lake City, United States",
  "San Antonio, United States",
  "San Diego, United States",
  "San Francisco, United States",
  "San Jose, United States",
  "Seattle, United States",
  "St. Louis, United States",
  "Tampa, United States",
  "Washington, United States",
  "Calgary, Canada",
  "Edmonton, Canada",
  "Halifax, Canada",
  "Montreal, Canada",
  "Ottawa, Canada",
  "Quebec City, Canada",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Winnipeg, Canada",
  "Cancún, Mexico",
  "Guadalajara, Mexico",
  "Mexico City, Mexico",
  "Monterrey, Mexico",
  "Puebla, Mexico",
  "Tijuana, Mexico",
  "Belize City, Belize",
  "Guatemala City, Guatemala",
  "Havana, Cuba",
  "Kingston, Jamaica",
  "Managua, Nicaragua",
  "Nassau, Bahamas",
  "Panama City, Panama",
  "San José, Costa Rica",
  "San Juan, Puerto Rico",
  "San Salvador, El Salvador",
  "Santo Domingo, Dominican Republic",
  "Tegucigalpa, Honduras",

  // South America
  "Asunción, Paraguay",
  "Barranquilla, Colombia",
  "Belo Horizonte, Brazil",
  "Bogotá, Colombia",
  "Brasília, Brazil",
  "Buenos Aires, Argentina",
  "Caracas, Venezuela",
  "Cartagena, Colombia",
  "Cayenne, French Guiana",
  "Córdoba, Argentina",
  "Curitiba, Brazil",
  "Fortaleza, Brazil",
  "Georgetown, Guyana",
  "Guayaquil, Ecuador",
  "La Paz, Bolivia",
  "Lima, Peru",
  "Medellín, Colombia",
  "Montevideo, Uruguay",
  "Paramaribo, Suriname",
  "Porto Alegre, Brazil",
  "Quito, Ecuador",
  "Recife, Brazil",
  "Rio de Janeiro, Brazil",
  "Rosario, Argentina",
  "Salvador, Brazil",
  "Santa Cruz, Bolivia",
  "Santiago, Chile",
  "São Paulo, Brazil",
  "Sucre, Bolivia",

  // Western & Northern Europe
  "Amsterdam, Netherlands",
  "Antwerp, Belgium",
  "Basel, Switzerland",
  "Belfast, United Kingdom",
  "Bergen, Norway",
  "Berlin, Germany",
  "Bern, Switzerland",
  "Birmingham, United Kingdom",
  "Bonn, Germany",
  "Bordeaux, France",
  "Bremen, Germany",
  "Brussels, Belgium",
  "Cardiff, United Kingdom",
  "Cologne, Germany",
  "Copenhagen, Denmark",
  "Dublin, Ireland",
  "Düsseldorf, Germany",
  "Edinburgh, United Kingdom",
  "Frankfurt, Germany",
  "Geneva, Switzerland",
  "Genoa, Italy",
  "Glasgow, United Kingdom",
  "Gothenburg, Sweden",
  "Hamburg, Germany",
  "Helsinki, Finland",
  "Leeds, United Kingdom",
  "Liverpool, United Kingdom",
  "London, United Kingdom",
  "Luxembourg City, Luxembourg",
  "Lyon, France",
  "Malmö, Sweden",
  "Manchester, United Kingdom",
  "Marseille, France",
  "Munich, Germany",
  "Nantes, France",
  "Nice, France",
  "Oslo, Norway",
  "Paris, France",
  "Reykjavik, Iceland",
  "Rotterdam, Netherlands",
  "Stavanger, Norway",
  "Stockholm, Sweden",
  "Strasbourg, France",
  "Stuttgart, Germany",
  "Tampere, Finland",
  "The Hague, Netherlands",
  "Toulouse, France",
  "Trondheim, Norway",
  "Utrecht, Netherlands",
  "Zurich, Switzerland",

  // Southern Europe
  "Alicante, Spain",
  "Athens, Greece",
  "Barcelona, Spain",
  "Bari, Italy",
  "Bilbao, Spain",
  "Bologna, Italy",
  "Florence, Italy",
  "Lisbon, Portugal",
  "Madrid, Spain",
  "Malaga, Spain",
  "Milan, Italy",
  "Naples, Italy",
  "Palermo, Italy",
  "Palma de Mallorca, Spain",
  "Porto, Portugal",
  "Rome, Italy",
  "Seville, Spain",
  "Andorra la Vella, Andorra",
  "Monaco, Monaco",
  "Nicosia, Cyprus",
  "Thessaloniki, Greece",
  "Turin, Italy",
  "Valencia, Spain",
  "Valletta, Malta",
  "Venice, Italy",
  "Verona, Italy",

  // Central & Eastern Europe
  "Baku, Azerbaijan",
  "Belgrade, Serbia",
  "Bratislava, Slovakia",
  "Brno, Czech Republic",
  "Bucharest, Romania",
  "Budapest, Hungary",
  "Chisinau, Moldova",
  "Cluj-Napoca, Romania",
  "Gdańsk, Poland",
  "Kraków, Poland",
  "Kyiv, Ukraine",
  "Lviv, Ukraine",
  "Minsk, Belarus",
  "Tbilisi, Georgia",
  "Yerevan, Armenia",
  "Podgorica, Montenegro",
  "Prague, Czech Republic",
  "Pristina, Kosovo",
  "Riga, Latvia",
  "Sarajevo, Bosnia and Herzegovina",
  "Skopje, North Macedonia",
  "Sofia, Bulgaria",
  "Tallinn, Estonia",
  "Tirana, Albania",
  "Vilnius, Lithuania",
  "Warsaw, Poland",
  "Wrocław, Poland",
  "Zagreb, Croatia",
  "Ljubljana, Slovenia",
  "Moscow, Russia",
  "Novosibirsk, Russia",
  "Saint Petersburg, Russia",
  "Vienna, Austria",

  // Middle East
  "Abu Dhabi, United Arab Emirates",
  "Amman, Jordan",
  "Ankara, Turkey",
  "Baghdad, Iraq",
  "Bahrain (Manama), Bahrain",
  "Beirut, Lebanon",
  "Damascus, Syria",
  "Doha, Qatar",
  "Dubai, United Arab Emirates",
  "Haifa, Israel",
  "Istanbul, Turkey",
  "Izmir, Turkey",
  "Jeddah, Saudi Arabia",
  "Jerusalem, Israel",
  "Kuwait City, Kuwait",
  "Muscat, Oman",
  "Riyadh, Saudi Arabia",
  "Sana'a, Yemen",
  "Tehran, Iran",
  "Tel Aviv, Israel",

  // Africa
  "Abidjan, Ivory Coast",
  "Abuja, Nigeria",
  "Accra, Ghana",
  "Addis Ababa, Ethiopia",
  "Alexandria, Egypt",
  "Algiers, Algeria",
  "Antananarivo, Madagascar",
  "Bamako, Mali",
  "Bujumbura, Burundi",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "Casablanca, Morocco",
  "Conakry, Guinea",
  "Dakar, Senegal",
  "Dar es Salaam, Tanzania",
  "Djibouti City, Djibouti",
  "Douala, Cameroon",
  "Durban, South Africa",
  "Freetown, Sierra Leone",
  "Gaborone, Botswana",
  "Harare, Zimbabwe",
  "Johannesburg, South Africa",
  "Kampala, Uganda",
  "Khartoum, Sudan",
  "Kigali, Rwanda",
  "Kinshasa, Democratic Republic of the Congo",
  "Lagos, Nigeria",
  "Libreville, Gabon",
  "Lusaka, Zambia",
  "Luanda, Angola",
  "Marrakesh, Morocco",
  "Maputo, Mozambique",
  "Mogadishu, Somalia",
  "Mombasa, Kenya",
  "Nairobi, Kenya",
  "N'Djamena, Chad",
  "Nouakchott, Mauritania",
  "Port Louis, Mauritius",
  "Pretoria, South Africa",
  "Rabat, Morocco",
  "Tripoli, Libya",
  "Tunis, Tunisia",
  "Windhoek, Namibia",
  "Yaoundé, Cameroon",

  // South & Central Asia
  "Ahmedabad, India",
  "Almaty, Kazakhstan",
  "Ashgabat, Turkmenistan",
  "Astana, Kazakhstan",
  "Bangalore, India",
  "Bishkek, Kyrgyzstan",
  "Chennai, India",
  "Colombo, Sri Lanka",
  "Dhaka, Bangladesh",
  "Dushanbe, Tajikistan",
  "Hyderabad, India",
  "Islamabad, Pakistan",
  "Jaipur, India",
  "Kabul, Afghanistan",
  "Karachi, Pakistan",
  "Kathmandu, Nepal",
  "Kolkata, India",
  "Lahore, Pakistan",
  "Mumbai, India",
  "New Delhi, India",
  "Pune, India",
  "Samarkand, Uzbekistan",
  "Tashkent, Uzbekistan",
  "Thimphu, Bhutan",

  // East & Southeast Asia
  "Bandung, Indonesia",
  "Bangkok, Thailand",
  "Beijing, China",
  "Busan, South Korea",
  "Cebu City, Philippines",
  "Chengdu, China",
  "Chiang Mai, Thailand",
  "Chongqing, China",
  "Da Nang, Vietnam",
  "Denpasar, Indonesia",
  "Fukuoka, Japan",
  "Guangzhou, China",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Hong Kong, China",
  "Jakarta, Indonesia",
  "Kaohsiung, Taiwan",
  "Kuala Lumpur, Malaysia",
  "Kyoto, Japan",
  "Macau, China",
  "Manila, Philippines",
  "Medan, Indonesia",
  "Nagoya, Japan",
  "Nanjing, China",
  "Osaka, Japan",
  "Penang, Malaysia",
  "Phnom Penh, Cambodia",
  "Pyongyang, North Korea",
  "Sapporo, Japan",
  "Seoul, South Korea",
  "Shanghai, China",
  "Shenzhen, China",
  "Singapore, Singapore",
  "Surabaya, Indonesia",
  "Taipei, Taiwan",
  "Tokyo, Japan",
  "Ulaanbaatar, Mongolia",
  "Vientiane, Laos",
  "Wuhan, China",
  "Xi'an, China",
  "Yangon, Myanmar",
  "Yokohama, Japan",

  // Oceania
  "Adelaide, Australia",
  "Auckland, New Zealand",
  "Brisbane, Australia",
  "Canberra, Australia",
  "Christchurch, New Zealand",
  "Darwin, Australia",
  "Gold Coast, Australia",
  "Hobart, Australia",
  "Melbourne, Australia",
  "Nouméa, New Caledonia",
  "Perth, Australia",
  "Port Moresby, Papua New Guinea",
  "Port Vila, Vanuatu",
  "Suva, Fiji",
  "Sydney, Australia",
  "Wellington, New Zealand",
]

export const WORLD_CITIES: string[] = [...RAW_CITIES].sort((a, b) => a.localeCompare(b))
